### ISSUE TITLE
Handling char Java primitives in kernel.

### ISSUE THREAD

**Issue by vsilaev** [beehive-lab/TornadoVM#108]
**Describe the bug**
It looks like `char` Java primitive type is not handled well in kernels, and the higher byte is set to some random value.
Discovered in test `uk.ac.manchester.tornado.unittests.arrays.TestArrays#testVectorChars`

**How To Reproduce**
Run arrays test from std. test package:
```
$ tornado -Dtornado.unittests.verbose=True -Xmx6g -Dtornado.recover.bailout=False  uk.ac.manchester.tornado.unittests.tools.TornadoTestRunner  uk.ac.manchester.tornado.unittests.arrays.TestArrays
```

In the output under some rare conditions (not always) the following output is shown:
```
        Running test: testVectorChars            ................  [FAILED]
                \_[REASON] expected:<102> but was:<16486>
```
or
```
        Running test: testVectorChars            ................  [FAILED]
                \_[REASON] expected:<102> but was:<25958>
```
If you pay attention, 102 = 0x**66**, but 16486 = 0x40**66** and 25958=0x65**66**.
You may notice the pattern -- the lowest byte in word is set correctly (0x66 corresponds to char 'f' assigned in kernel code), but the highest byte takes some random value.

Interesting, I changed 'f' to '\u3333' in code to re-run the test -- but same error appears periodically. So even if char takes two bytes it's still processed incorrectly in kernel.

The next interesting point is that `testVectorCharsMessage` always works correctly - but ther char is summed up with int.

**Expected behavior**
Test should pass and the char value must be assigned correctly.

**Computing system setup (please complete the following information):**
 - OS: Windows 10
 - OpenCL 1.2 (NVIDIA or AMD) 
 - TornadoVM 0.9

**Additional context**
Tested with both NVIDIA & AMD GPU-s

**Comment by jjfumero** [comment]
Thank you for the report. I can't reproduce the error. Which OpenCL driver/s are you using? Is it only for the OpenCL backend, or you get the same error for PTX? 

My driver setup (for Linux) 
* NVIDIA 460.80 for Linux
* Intel HD Graphics 21.19.19792 
* Intel CPU Runtime: 18.1.0.0920

**Comment by vsilaev** [comment]
![s1](https://user-images.githubusercontent.com/3337603/119123799-a25ef880-ba38-11eb-9cff-3d19fc1f632c.png)
![s2](https://user-images.githubusercontent.com/3337603/119123827-a8ed7000-ba38-11eb-8143-07cb96364ed4.png)

**Comment by vsilaev** [comment]
/drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/mm/PrimitiveSerialiser.java -- ignores CHAR and BYTE
/drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/mm/OCLObjectWrapper.java -- ignores CHAR and CHAR[] when reading field value and wrapping array field.

**Comment by vsilaev** [comment]
Seems to be fixed with this commit:
https://github.com/beehive-lab/TornadoVM/commit/df3150beff6831350787e91c1d1b7dcd3dbe98e4

**Comment by vsilaev** [comment]
Closing the issue - it looks like it was indeed "accidentally" fixed
