### ISSUE TITLE
Endianness of OpenCL driver

### ISSUE THREAD

**Issue by vsilaev** [beehive-lab/TornadoVM#110]
This is not actually a bug but rather a question - as long as I can't get necessary hardware/software to test.
Per my understanding of the code, the OpenCL driver directly "projects" java arrays  as OpenCL buffers (with elements larger than a byte like long or double).

As long as Java always stores primitives in little endian format, does it mean that TornadoVM only support environments (combo of hardware & software) with little endian encoding?

Did you test on any platform with Big Endian? Like ones mentioned here - https://en.wikipedia.org/wiki/Endianness (OpenRISC,  IBM z/Architecture, SPARC + corresponding OS like AIX / Solaris)? Or all such platforms are considered obsolete?

Or do you use some OpenCL-specific annotations in generated kernels to enforce little-endianness?

**Comment by jjfumero** [comment]
> As long as Java always stores primitives in little endian format, does it mean that TornadoVM only support environments (combo of hardware & software) with little endian encoding?

No. TornadoVM queries the device's properties and obtains the endianness of the device. GPUs and FPGAs are usually little-endian, but TornadoVM always queries the endianness before setting the order of the byte arrays. 

> Did you test on any platform with Big Endian? Like ones mentioned here - https://en.wikipedia.org/wiki/Endianness (OpenRISC, IBM z/Architecture, SPARC + corresponding OS like AIX / Solaris)? Or all such platforms are considered obsolete?

No, we haven't tested on those platforms.

**Comment by vsilaev** [comment]
> No. TornadoVM queries the device's properties and obtains the endianness of the device. GPUs and FPGAs are usually little-endian, but TornadoVM always queries the endianness before setting the order of the byte arrays.

You don't. Take a look at `OCLCommandQueue` -  you are using fixed endianness for API like `getContextId` or `getDeviceId`, however all calls to `enqueueWrite` and `enqueueRead` are just passing Java arrays as is to JNI methods, where direct access is used to array content, and this content is always in little endian (Java std.)

**Comment by jjfumero** [comment]
Yes, we do. The pointer to the heap is set in the call stack. This is has a byte-buffer that has the endianess from the device. Otherwise, it does not work.

Additionally, we register the Graal Architecture with the correct endianness from the device.

**Comment by vsilaev** [comment]
> Yes, we do. The pointer to the heap is set in the call stack. This is has a byte-buffer that has the endianess from the device. Otherwise, it does not work.

From what I see there are indeed `OCLByteBuffer` and `OCLCallStack` that applies endianness. However, what about this sequence:
1. `TornadoVM` executes `streamIn` in `OCLTornadoDevice` passing a long[] as first argument
2.  `OCLTornadoDevice` gets corresponding `ObjectBuffer` that corresponds to `OCLLongArrayWrapper` (subclass of `OCLArrayWrapper`) and invokes `OCLLongArrayWrapper.writeArrayData` 
3. The call is delegated to `OCLDeviceContext.writeBuffer(long bufferId, long offset, long bytes, long[] array, long hostOffset, int[] waitEvents)`
4. Further this is delegated to OCLCommandQueue and ends up with JNI call were original array content is used exactly, without any endianness correction.

What I miss? In which call endianness is changed from Little Endian (java) to Device-specific endianness?

**Comment by stratika** [comment]
Coming back to this issue, in Step 2, the `OCLTornadoDevice.java` will invoke `enqueueWrite` on an `ObjectBuffer` object ([line 604](https://github.com/beehive-lab/TornadoVM/blob/develop/drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/runtime/OCLTornadoDevice.java)). The `enqueueWrite()` method that is being invoked is implemented in the OCLArrayWrapper.java class ([line 194](https://github.com/beehive-lab/TornadoVM/blob/develop/drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/mm/OCLArrayWrapper.java)). In case that batch processing is not used, the `buildArrayHeader` method is called. This method invokes the `getArrayHeader` method ends up to line 250 of [`OCLArrayWrapper.java`](https://github.com/beehive-lab/TornadoVM/blob/develop/drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/mm/OCLArrayWrapper.java), where the `getSubBuffer` method returns a new `OCLByteBuffer` object.

The returned `OCLByteBuffer` object is configured with the correct endianness based on the properties of the OpenCL driver, and upon this buffer will be performed the data movement via the `enqueueWrite` call.

Let me know if you need any further clarification. I hope this addresses your question. For the record, as far as I know, we have not tested TornadoVM in hardware devices that support Big Endianness.

**Comment by vsilaev** [comment]
The part you described is about writing header, however in lines 203 and 213 of the [OCLArrayWrapper.java](https://github.com/beehive-lab/TornadoVM/blob/develop/drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/mm/OCLArrayWrapper.java) there are calls to the `writeArrayData` that writes array BODY, and here no endianness is taken on account in subclasses (like `OCLLongArrayWrapper.java`).

**Comment by stratika** [comment]
I tried an experiment with an `int[]` array for the TornadoVM `VectorAddInt` example to understand how the data are organized currently. I initialized the input vector with different integer values:
For example: ```0, 1, 2, 3, ...```

Then I printed the array in byte form from two points: 
1. The `enqueueWrite` method in `[OCLCommandQueue.java](https://github.com/beehive-lab/TornadoVM/blob/master/drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLCommandQueue.java)` class (line 222). In this method, I converted the array to a byte array and printed each byte.
2. The `transferFromHostToDevice` function in `[OCLCommandQueue.cpp](https://github.com/beehive-lab/TornadoVM/blob/master/drivers/opencl-jni/src/main/cpp/source/OCLCommandQueue.cpp)` which is in the JNI. This function has the data already in byte form.

For point 1: the data were printed in this order: ```0000 0001 0002 0003```
For point 2: the data were printed in this order: ```0000 1000 2000 3000```

From this example, it seems that Java is Big Endian, the JVM converts the data to be in the endianness of the system when the execution goes to JNI which is written in C++. In my case, my CPU is Little Endian.

**Comment by vsilaev** [comment]
I'm afraid that this is an unfair experiment - when converting to the byte array in Java, the JDK classes has a context to do a right conversion from LITTELE to BIG endian. The fair test would be to pass 2 direct byte buffers, one in Little and one in Big endian, to the JNI and check whether or not the conversion is applied when data is passed to the JNI level - and I doubt this is true.

**Comment by stratika** [comment]
I do not understand the word `unfair`. Feel free to conduct such experiment and report your findings.

**Comment by kotselidis** [comment]
I would like to reset the discussion on this thread. @vsilaev is there any specific device that you use that requires big endian? We have not encountered one or we foresee that we will use in the future. If, as the initial post states, this is just for information, then I propose to close the issue and if a device that we can test becomes available then we can assess it.

**Comment by vsilaev** [comment]
Ok, agree to close the discussion.
Just the latest hint - arrays in Java are stored in Little Endian, hence all your JNI code that uses direct array addresses works on Little Endian CPU.
The proof (should be added to the example above):
```java
        int[] initial = {1, 2, 3, 4, 5};
        long addr = UNSAFE.arrayBaseOffset(int[].class);
        System.out.print("Bytes in int[] array: ");
        String separator = "";
        for (int i = 0, size = initial.length * Integer.BYTES; i < size; i++) {
            System.out.print(separator);
            byte b = UNSAFE.getByte(initial, addr + i);
            System.out.print(b);
            separator = ",";
        }
        System.out.println();
```
OUTPUT
```
Bytes in int[] array: 1,0,0,0,2,0,0,0,3,0,0,0,4,0,0,0,5,0,0,0
```
You can see that output matches `Byte buffer, via UNSAFE (LITTLE_ENDIAN)` from the above.

**Comment by stratika** [comment]
Thanks @vsilaev. I will close this issue.
