### ISSUE TITLE
Invalid binary in AWS EC2 F1 instance, while AFI is not ready

### ISSUE THREAD

**Issue by stratika** [beehive-lab/TornadoVM#116]
**Is your feature request related to a problem? Please describe.**
Due to the AWS FPGA toolchain, once the Xilinx bitstream is generated it cannot be immediately executed. It requires first to create an Amazon FPGA Image (AFI). 

In TornadoVM, the user invokes the `aws_post_processing.sh` script which creates an Amazon FPGA Image (AFI), updates the link of the FPGA binary and uploads a description to an AWS S3 bucket. The creation of the AFI takes around 30-40 minutes. 

As a result, TornadoVM will crash the first time it aims to execute the AFI with an error in `clBuildProgramWithBinary`, which is expected, as AFI is not ready. What do you think about this case? I guess it is not important, as users can query the status of the AFI and then execute on the FPGA. But, I would like to listen any opinions.

**Describe the solution you'd like**
I was thinking of a solution that has the following:
1. The `aws_post_processing.sh` script to be automatically triggered by the TornadoVM runtime.
2. During the time that the AFI is not ready, the VM to be shutdown or somehow make it hold till the AFI status is ready.

**Comment by jjfumero** [comment]
This is the AWS workflow to compile the bitstream. As you said, we can shutdown the TornadoVM execution while the bitstream is being created. Once the bitstream is finalized, users can run TornadoVM as usual. 

Another option is to only do a pre-compilation (AoT mode) when compiling on Amazon instances.

**Comment by jjfumero** [comment]
@stratika , I think this can be closed since was already merged.
