### ISSUE TITLE
Port all python scripts from version 2 to 3 

### ISSUE THREAD

**Issue by jjfumero** [beehive-lab/TornadoVM#13]
Since Python 2.7 is no longer supported, rewrite all python script to use Python 3.X instead of 2.X.

**Comment by jjfumero** [comment]
This is now done by @gigiblender.

**Comment by gigiblender** [comment]
@jjfumero I think this can also be closed

**Comment by jjfumero** [comment]
Update here: https://github.com/beehive-lab/TornadoVM/commit/d55e3de1d73d5c0c0635f03fb6f51d9713c0f12a
