### ISSUE TITLE
Maven settings.xml file gets overwritten (instead of merged)

### ISSUE THREAD

**Issue by gwinstanley** [beehive-lab/TornadoVM#146]
**Describe the bug**
During compilation, the `scripts/updateMavenSettings.py` script overwrites any existing `~/.m2/settings.xml` file.

**How To Reproduce**
Build the project with an existing `~/.m2/settings.xml` file in place.

**Expected behavior**
TornadoVM custom settings to be merged into existing file instead of overwriting it.

**Computing system setup (please complete the following information):**
 - OS: macOS 10.14.6
 - OpenCL Version 1.2
 - TornadoVM commit id c61f38854

**Comment by jjfumero** [comment]
Thank you @gwinstanley  for the report.
 This is now fixed: https://github.com/beehive-lab/TornadoVM/commit/0642e07634fb929573f012d2949a0852137f4ff2 

I will close this issue. Feel free to open new issues if you encounter new problems.
