### ISSUE TITLE
TaskSchedule::task(Task13|Task14) returns TornadoAPI object.

### ISSUE THREAD

**Issue by yazun** [beehive-lab/TornadoVM#155]
**Describe the bug**
Seems there's discrepancy in the TaskSchedule

https://github.com/beehive-lab/TornadoVM/blob/master/tornado-api/src/main/java/uk/ac/manchester/tornado/api/TaskSchedule.java#L211

for Task13 and Task14 params returns TornadoAPI which breaks the usual pattern for TaskSchedule usage.

**How To Reproduce**
```java
TaskSchedule task = new TaskSchedule("PeriodSearch") //
                .task("t0", MethodLeastSquareGPU::computeGPU, <13 or 14 params>)
```
will not compile complaining about type mismatach.
**Expected behavior**
Should always return TaskSchedule.

**Computing system setup (please complete the following information):**
 - OS: MACOS
 - OpenCL NA
 - TornadoVM dev 0.13

**Additional context**

**Comment by jjfumero** [comment]
Thank you @yazun , good catch. We will fix this.
