### ISSUE TITLE
Support for inverse trigonometric functions

### ISSUE THREAD

**Issue by Vinhixus** [beehive-lab/TornadoVM#178]
**Is your feature request related to a problem? Please describe.**
TornadoVM bails out to sequential when using the functions Math.asin(), Math.acos() and Math.atan2().
The TornadoMath class also does not have an equivalent function for these operations.
Please note that Math.atan() and Math.atan2() are two different functions.

**Describe the solution you'd like**
Add support for the functions above and implement TornadoMath.floatAsin(), TornadoMath.floatAcos(), TornadoMath.floatAtan2().

**Describe alternatives you've considered**
N/A

**Additional context**
The issues can be recreated using the simple code snippets below:
(Math.asin() can be replaced with Math.acos() and Math.atan2() to replicate the issue for the respective functions)

```
import uk.ac.manchester.tornado.api.TaskSchedule;
import uk.ac.manchester.tornado.api.annotations.Parallel;

@SuppressWarnings("PrimitiveArrayArgumentToVarargsMethod")
public class Tornado {

    public static final int ARRAY_SIZE = 100;

    private static void test(float[] output) {
        for (@Parallel int x = 0; x < ARRAY_SIZE; x++)
            output[x] = (float) Math.asin(x);
    }

    public static void main(String[] args) {

        // Output array
        float[] output = new float[ARRAY_SIZE];

        // Task
        TaskSchedule ts = new TaskSchedule("s0");
        ts.task("t0", Tornado::test, output);
        ts.streamOut(output);

        // Execution
        ts.execute();

        // Results
        System.out.print("Output: ");
        for (int i = 0; i < ARRAY_SIZE; i++) System.out.print(output[i] + ", ");
        System.out.println();
    }
}
```

**Comment by jjfumero** [comment]
Thank you @Vinhixus.
  This affects all backends? OpenCL, PTX and SPIRV? or just one of the backends?

**Comment by jjfumero** [comment]
Update: After a sync call with @Vinhixus , this affects all backends. 

@gigiblender, let's focus first on the OpenCL and SPIR-V. Then we will design a strategy for the PTX backend.

**Comment by jjfumero** [comment]
This is already merged. https://github.com/beehive-lab/TornadoVM/commit/8a3b1e9574654c668de5aee12bf66b66c18142b0
