### ISSUE TITLE
[Feature Request] Support Live Task Migration across backends

### ISSUE THREAD

**Issue by jjfumero** [beehive-lab/TornadoVM#184]
Support Live Task Migration across backends. 

Currently, TornadoVM launches an exception when the backend is dynamically switched. Ideally we should be able to run with any backend in any order and dynamically switch across them. 

E.g., OpenCL <-> SPIR-V <-> PTX 

This is useful for demos such as Ray-Tracer.

**Comment by stratika** [comment]
A fix regarding this issue is currently [merged](https://github.com/beehive-lab/TornadoVM/commit/be27e0efe026cf90ac5c28de4c474fdb3388a8a1). I will close the issue.
