### ISSUE TITLE
Unit-tests failing on macOS M1 Pro

### ISSUE THREAD

**Issue by stratika** [beehive-lab/TornadoVM#208]
### Describe the bug 
Currrently in macOS and in particular on MacBooks with Apple M1 Pro, there are several unit-tests failing due to the lack of extensions supported by the drivers.

For example, in my system I see that `clinfo` does not report the extension for double precission support: [cl_khr_fp64](https://registry.khronos.org/OpenCL/sdk/1.0/docs/man/xhtml/cl_khr_fp64.html). This causes many unit-tests to fail.

### How To Reproduce

Provide a **test-case** and **instructions** of how to reproduce the issue.

```bash
make tests

==================================================
              Unit tests report 
==================================================

{'[PASS]': 407, '[FAILED]': 97, '[UNSUPPORTED]': 23}
Coverage [PASS/(PASS+FAIL)]: 80.75%
Coverage [PASS/(PASS+FAIL+UNSUPPORTED)]: 77.23%

==================================================
```

### Expected behavior 
The support for `double` floating point precision can be retrieved by the drivers at runtime, and then the unit-tests that target double floating point precision can be reported as unsupported tests.

### Computing system setup (please complete the following information):
 - OS: macOS Monterey
 - OpenCL and Driver versions: 1.2 1.0
 - If applicable, PTX and CUDA Driver versions: Not related
 - If applicable, Level Zero & SPIR-V Versions: Not related
 - TornadoVM commit id: `develop`

---------------------------------------------------------------------

**Comment by jjfumero** [comment]
We have a custom exception for this. We should raise this exception. This works for the new Intel GPUs. I wonder why it does not work for OSx. Let's sync when you are back,

**Comment by stratika** [comment]
> We have a custom exception for this. We should raise this exception. This works for the new Intel GPUs. I wonder why it does not work for OSx. Let's sync when you are back,

oh, I was not aware of that exception. Sure, let's meet next week to sync.

**Comment by jjfumero** [comment]
Yes, `TornadoDeviceFP64NotSupported` is the same as `double`.  We should use this one.

**Comment by stratika** [comment]
The problem is observed when running on the GPU of MacBook M1 Pro, and on Intel Integrated GPUs for the OpenCL backend. The reason is that double precision floating point arithmetic is not supported in these devices. Thus, some unit-tests that use `double` types are failing.

Here is the report from M1:
```bash
==================================================
              Unit tests report 
==================================================
{'[PASS]': 407, '[FAILED]': 97, '[UNSUPPORTED]': 23}
Coverage [PASS/(PASS+FAIL)]: 80.75%
Coverage [PASS/(PASS+FAIL+UNSUPPORTED)]: 77.23%
==================================================
```

I have added a check in the device (OCLTornadoDevice, PTXTornadoDevice) in the `compileTask` to check if any arguments of a task require double floating precision, while the device does not support it. If this is the case, an exception (`TornadoDeviceFP64NotSupported`) is thrown.

- For PTX, I saw [here](https://en.m.wikipedia.org/wiki/CUDA#Version_features_and_specifications) that all versions of compute capability larger than 1.3, support double floating point arithmetic. This is quite old, so practically all CUDA devices support this now. Do you think I should revert the check for PTX? Or should we keep it? (**Question 1**)

- For SPIRV this was not the case, as a check is already present in the backend that queries if FP64 is not supported in order to throw the same exception. 

The result now is:
```bash
==================================================
              Unit tests report 
==================================================

{'[PASS]': 404, '[FAILED]': 23, '[UNSUPPORTED]': 100}
Coverage [PASS/(PASS+FAIL)]: 94.61%
Coverage [PASS/(PASS+FAIL+UNSUPPORTED)]: 76.66%

==================================================
```

Finally, there is a tricky case in which a Java method may not use `double` types, but because internally it consumes the Math functions it may generate double variables. This case currently fails and it is represented by the `testDFTDouble` test case. Any advice on that matter? (**Question 2**) It is a bit tricky to find the right place to perform such a check. 

```bash
tornado-test -V uk.ac.manchester.tornado.unittests.compute.ComputeTests#testDFTDouble
```

@jjfumero, let me know of your thoughts for the two questions.

**Comment by jjfumero** [comment]
Hi @stratika , 
   for the PTX backend, we can avoid the check since we support CUDA >= 10.0.

Regarding the SPIR-V, yes I recall now that's the right place to do the check. So for the OpenCL backend, we should do the same: compile to get the Low-Tier IR and traverse the final IR before generating OpenCL C code to obtain fp64 operands.

**Comment by stratika** [comment]
I will close this issue, as a fix has been merged.
