### ISSUE TITLE
Gradle issue

### ISSUE THREAD

**Issue by offeex** [beehive-lab/TornadoVM#232]
Hello, why i can't import TornadoVM with gradle?
I imported it's jar files with intellij, here's the error i get
![image](https://user-images.githubusercontent.com/64991049/221614201-4f5f3289-f912-4da9-9204-c4af1c20a22a.png)

I would like to have a way to set TornadoVM  in gradle

**Comment by jjfumero** [comment]
Hi @offeex .
   TornadoVM is built using `maven`. If you want to use another build system you need to also build the dependencies. 
We get the API from a copy of all JAR files we have in GitHub.

The Maven dependency is as follows:

```xml
<repositories>
    <repository>
        <id>universityOfManchester-graal</id>
        <url>https://raw.githubusercontent.com/beehive-lab/tornado/maven-tornadovm</url>
    </repository>
</repositories>

<dependencies>
<dependency>
    <groupId>tornado</groupId>
    <artifactId>tornado-api</artifactId>
    <version>0.15</version>
</dependency>
<dependency>
    <groupId>tornado</groupId>
    <artifactId>tornado-matrices</artifactId>
    <version>0.15</version>
</dependency>
</dependencies>
```

And all JAR files are stored here: https://github.com/beehive-lab/TornadoVM/tree/maven-tornadovm

**Comment by jjfumero** [comment]
I close this issue since this build process is not the one TornadoVM has.
