### ISSUE TITLE
doesn't work in IDE

### ISSUE THREAD

**Issue by offeex** [beehive-lab/TornadoVM#233]
I've installed TornadoVM according to installation instruction (on Arch Linux), set up maven project, and here's results.
![image](https://user-images.githubusercontent.com/64991049/221641405-82260ea7-3c0c-4576-81f0-99e573b508bd.png)
Anybody can explain how do i set it up working in IDE? I want to just run it from Main.java

**Comment by offeex** [comment]
I just built it, all cool, now it just doesn't want to work even in CLI 
![image](https://user-images.githubusercontent.com/64991049/221642309-8af2c82d-ba6c-41fa-ac55-8eca60333178.png)

**Comment by offeex** [comment]
![image](https://user-images.githubusercontent.com/64991049/221643752-d655cec2-03a3-49f9-ab61-bc0b9efb8743.png)

**Comment by jjfumero** [comment]
We are closing this issue. This is more a question rather than an issue. If you still have questions, please use the `discussion` page from GitHub.
