### ISSUE TITLE
MonteCarloDynamic kernel failing on the Xilinx FPGA

### ISSUE THREAD

**Issue by stratika** [beehive-lab/TornadoVM#24]
**Describe the bug**
I noticed a problem with the Montecarlo kernel in the dynamic package for all the sizes, when executing on the Xilinx KCU1500 FPGA. There is no error in the compilation, but the kernel does not finish and it causes failures at the driver level regarding the dma. The problem seems like this:
```
[  815.440478] xocl:engine_status_dump: SG engine 0-H2C1-MM status: 0x00000000:
[  815.440480] xocl:engine_status_dump: SG engine 0-H2C0-MM status: 0x00000001: BUSY
[  815.440483] xocl:transfer_abort: abort transfer 0x000000009584ae00, desc 11, engine desc queued 0.
[  815.440487] xocl:transfer_abort: abort transfer 0x00000000d2360335, desc 1, engine desc queued 0.
[  815.440505] xocl_mm_xdma mm_dma.v5.u.256: xdma_migrate_bo: DMA failed, Dumping SG Page Table
[  815.440508] xocl_mm_xdma mm_dma.v5.u.256: xdma_migrate_bo: DMA failed, Dumping SG Page Table
[  815.440516] xocl_mm_xdma mm_dma.v5.u.256: xdma_migrate_bo: 0, 0xf3ce7c000
[  815.440521] xocl_mm_xdma mm_dma.v5.u.256: xdma_migrate_bo: 1, 0xf3d800000
[  815.440526] xocl_mm_xdma mm_dma.v5.u.256: xdma_migrate_bo: 2, 0xf3d400000
[  815.440531] xocl_mm_xdma mm_dma.v5.u.256: xdma_migrate_bo: 3, 0xf3f000000
[  815.440536] xocl_mm_xdma mm_dma.v5.u.256: xdma_migrate_bo: 4, 0xf7d000000
[  815.440540] xocl_mm_xdma mm_dma.v5.u.256: xdma_migrate_bo: 5, 0xf4f800000
[  815.440545] xocl_mm_xdma mm_dma.v5.u.256: xdma_migrate_bo: 6, 0xf54800000
[  815.440550] xocl_mm_xdma mm_dma.v5.u.256: xdma_migrate_bo: 7, 0xf60400000
[  815.440554] xocl_mm_xdma mm_dma.v5.u.256: xdma_migrate_bo: 8, 0xf61c00000
[  815.440559] xocl_mm_xdma mm_dma.v5.u.256: xdma_migrate_bo: 9, 0xf3b800000
[  815.440568] xocl_mm_xdma mm_dma.v5.u.256: xdma_migrate_bo: 0, 0xf3821f000
```
This problem occurs only on the Xilinx KCU1500 FPGA. The Intel Nallatech Arria 10 FPGA is working both in emulation mode and the other two modes (Full Jit and AoT).

So, I did some work around and compared the previous kernel that was working (about 2 months old) and the current one. I took the body of the old kernel and applied two changes that we introduced in the latest version: 
a) altered the number regarding the frame number from 6 to 0. 
b) removed the private region parameter. 

The modified kernel seems to be working. So, the main difference between the two kernels is shown in the figure (Left kernel is the old one that is working, Right kernel is the new one that causes the problem):
![montecarlo_kernels diff](https://user-images.githubusercontent.com/34061419/86154945-a66de900-bafb-11ea-8ab3-ba36839c6d4f.png)

**How To Reproduce**
`tornado -Ds0.t0.device=0:1 -Xmx20g -Xms20g --printKernel --debug uk.ac.manchester.tornado.examples.dynamic.MontecarloDynamic 65536 default 1`

Note that device 0:1 is the `xilinx_kcu1500_dynamic_5_0 CL_DEVICE_TYPE_ACCELERATOR`

**Computing system setup (please complete the following information):**
 - OS: Ubuntu 18.04.02 LTS
 - OpenCL Version: 1.0 
 - TornadoVM commit id:  ed243aa

Any ideas? I am not familiar with this change about the `fma`.

**Comment by jjfumero** [comment]
Thank @stratika. Do you think the issue is the `FMA` instruction? This is supported from OpenCL 1.0

https://www.khronos.org/registry/OpenCL/sdk/1.0/docs/man/xhtml/fma.html

Can you substitute the `fma` to use separate instructions instead? Just to double-check that is the problem. 

Apart from that, the changes:
a) OpenCL frame: should not affect 
b) Private memory allocation for arrays: this might cause a problem is we get out of resources. But IMO, we should get an error after the kernel launch.

**Comment by stratika** [comment]
I have made the following change in the kernel that causes the problem and tested it in the AoT mode.
I replaced:  ```f_27  =  fma(f_16, f_16, f_26);``` with: 
```f_26  =  f_25 * f_25;
f_27  =  f_16 * f_16;
f_27  =  f_27 + f_26;
```

This kernel works and this is the result:
```
task info: s0.t0
	platform          : Xilinx
	device            : xilinx_kcu1500_dynamic_5_0 CL_DEVICE_TYPE_ACCELERATOR (available)
	dims              : 0
	global work offset: [0]
	global work size  : [65536]
	local  work size  : [64, 1, 1]
Total time:  1568569786 ns

Pi value (TornadoVM) : 3.1392822
Pi value (Sequential) : 3.1392822
```

So, it seems that since the Xilinx compiler did not result in any failures during compilation, the problem occurs at runtime and in particular in the Xilinx driver that comes with _Xilinx SDAccel 2018.2_. 

This problem may be solved in later versions that use VITIS and the [Xilinx Runtime Library (XRT)](https://www.xilinx.com/products/design-tools/vitis/xrt.html) (supported for versions > 2018.2). However, the KCU1500 FPGA is not officially supported by these software tools. 

I will try to see if the same issue occurs in the AWS cloud, where the XRT layer is available as it uses _SDAccel 2018.3_.

**Comment by jjfumero** [comment]
Thank Thanos. You can report this issue to the Xilinx OpenCL runtime.

**Comment by jjfumero** [comment]
I added a flag to disable this optimization. It is enabled by default.

https://github.com/beehive-lab/TornadoVM/pull/28

**Comment by stratika** [comment]
Just an update, I tried to reproduce the issue in the AWS EC2 F1 instance with AMI Version: 1.6.0. This instance uses SDAccel 2018.3, with a different driver. The problem did not occur, this is the log with the printed kernel:

```
tornado -Ds0.t0.device=0:0 -Dtornado.fpga.conf.file=/home/centos/repositories/TornadoVM-Internal/etc/aws_fpga.conf -Xmx20g -Xms20g --printKernel --debug uk.ac.manchester.tornado.examples.dynamic.MontecarloDynamic 65536 default 1
Montecarlo Computation
xclProbe found 1 FPGA slots with xocl driver running
__kernel void lookupBufferAddress(__global uchar *_heap_base, ulong _frame_base, __constant uchar *_constant_region, __local uchar *_local_region)
{

  __global ulong *_frame = (__global ulong *) &_heap_base[_frame_base];


  // BLOCK 0
  _frame[0]  =  (ulong) _heap_base;
}

Initialization time:  911231559 ns

[DEBUG] JIT compilation for the FPGA
Warning: -Dtornado.opencl.userelative was set to False. TornadoVM changed it to True because it is required for FPGA execution.
__attribute__((reqd_work_group_size(64,1,1)))
__kernel void computeMontecarlo(__global uchar *_heap_base, ulong _frame_base, __constant uchar *_constant_region, __local uchar *_local_region)
{
  ulong ul_0, ul_8; 
  float f_16, f_15, f_25, f_24, f_28, f_27, f_26; 
  long l_11, l_10, l_9, l_7, l_6, l_5, l_23, l_22, l_21, l_20, l_19, l_18, l_17, l_14, l_13, l_12; 
  int i_29, i_30, i_4, i_1, i_2, i_3; 

  __global ulong *_frame = (__global ulong *) &_heap_base[_frame_base];


  // BLOCK 0
  ul_0  =  (ulong) _frame[0];
  i_1  =  get_global_id(0);
  // BLOCK 1 MERGES [0 5 ]
  i_2  =  i_1;
  // BLOCK 2
  i_3  =  get_global_size(0);
  i_4  =  i_3 + i_2;
  l_5  =  (long) i_2;
  l_6  =  l_5 << 2;
  l_7  =  l_6 + 24L;
  ul_8  =  ul_0 + l_7;
  l_9  =  l_5 * 25214903917L;
  l_10  =  l_9 + 11L;
  l_11  =  l_10 & 281474976710655L;
  l_12  =  l_11 * 25214903917L;
  l_13  =  l_12 + 11L;
  l_14  =  l_13 & 268435455L;
  f_15  =  (float) l_14;
  f_16  =  f_15 / 2.68435456E8F;
  l_17  =  l_13 & 281474976710655L;
  l_18  =  l_17 * 25214903917L;
  l_19  =  l_18 + 11L;
  l_20  =  l_19 & 281474976710655L;
  l_21  =  l_20 * 25214903917L;
  l_22  =  l_21 + 11L;
  l_23  =  l_22 & 268435455L;
  f_24  =  (float) l_23;
  f_25  =  f_24 / 2.68435456E8F;
  f_26  =  f_25 * f_25;
  f_27  =  fma(f_16, f_16, f_26);
  f_28  =  sqrt(f_27);
  i_29  =  isless(1.0F, f_28);
  if(i_29 == 1)
  {
    // BLOCK 3
    *((__global float *) &_heap_base[ul_8])  =  0.0F;
  }
  else
  {
    // BLOCK 4
    *((__global float *) &_heap_base[ul_8])  =  1.0F;
  }
  // BLOCK 5 MERGES [4 3 ]
  i_30  =  i_4;
  i_2  =  i_30;
  // BLOCK 6
  return;
}

INFO: Could not load AFI for data retention, code: 18 - Loading in classic mode.
AFI load complete.
task info: s0.t0
	platform          : Xilinx
	device            : xilinx_aws-vu9p-f1-04261818_dynamic_5_0 CL_DEVICE_TYPE_ACCELERATOR (available)
	dims              : 1
	global work offset: [0]
	global work size  : [65536]
	local  work size  : [64, 1, 1]
Total time:  3027100882 ns

Pi value (TornadoVM) : 3.1392822
Pi value (Sequential) : 3.1392822
```

**Comment by stratika** [comment]
I think this issue can be closed.
