### ISSUE TITLE
[Proposal] Ordering of default list of devices visible in TornadoVM

### ISSUE THREAD

**Issue by jjfumero** [beehive-lab/TornadoVM#246]
**Is your feature request related to a problem? Please describe.**

TornadoVM's default device is the OS default device. This really depends on the installation process of the corresponding drivers and the runtimes (e.g., OpenCL and CUDA drivers)  for each device. The issue is that the default device may not be most efficient one, nor the most powerful one. 

**Describe the solution you'd like**

I propose to order the internal list of devices that TornadoVM has by providing first the best in terms of CC (compute capability). Additionally, we can request TornadoVM to provide a specific order. But we can investigate different orderings. 

This already happens per backend, but not per device within the selected backend. 

**Describe alternatives you've considered**

I would like to discuss this further: @mikepapadim , @stratika @kotselidis

**Comment by mikepapadim** [comment]
I have a two years old code that it does that based on the `global memory` and total `number work-items`.

**Comment by jjfumero** [comment]
Also, I suggest prioritizing per device type. 
1. Discrete GPUs (if available)
2. Integrated GPUs (if available)
3. Multi-core CPUs 
4. FPGA (either emulation or physical device).

**Comment by mikepapadim** [comment]
This is fixed with https://github.com/beehive-lab/TornadoVM/releases/tag/v0.15.1.
