### ISSUE TITLE
Unable to build in ubuntu 22

### ISSUE THREAD

**Issue by quantrpeter** [beehive-lab/TornadoVM#261]
Hi
   Unable to build in ubuntu 22

![image](https://github.com/beehive-lab/TornadoVM/assets/50471577/e91b7232-07d1-4859-8b80-e130e7addf7f)

![image](https://github.com/beehive-lab/TornadoVM/assets/50471577/15698859-7d5b-4945-b815-8c1f864657b8)

thanks

**Comment by stratika** [comment]
hi @quantrpeter, it is not very easy to spot why you get the error. Are you using the [automatic installation](https://tornadovm.readthedocs.io/en/latest/installation.html#a-automatic-installation) via the tornadovm-installer script, or the [manual installation](https://tornadovm.readthedocs.io/en/latest/installation.html#linux)?

Can you also provide some information regarding your platform? Do you have OpenCL and CUDA already installed?

**Comment by jjfumero** [comment]
Hi @quantrpeter , thank you for the report. Do you have OpenCL/CUDA drivers + SDK installed as well as the Intel Drivers? This brings the dynamic libraries needed to compile the JNI components of TornadoVM. 

Note that TornadoVM does not install GPU/FPGA drivers. This is done by the user.

**Comment by quantrpeter** [comment]
Hi @stratika , I am using auto install 

./scripts/tornadovm-installer --jdk jdk-17  --backend opencl,ptx,spirv

Hi @jjfumero 

I have OpenCL driver installed.

**Comment by jjfumero** [comment]
Could you provide the logs when compiling the JNI libraries? You can compile them directly:

e.g., The OpenCL C++ JNI library

```bash
cd $TORNADO_ROOT
cd /tornado-drivers/opencl-jni/src/main/cpp/
mkdir build
cd build 
cmake ..
make 
```

And send us the logs?  Maybe you need the JNI.h headers or some other dependencies.

**Comment by jjfumero** [comment]
BTW, if it helps, these are the instructions to build TornadoVM using a clean Ubuntu 22.04 docker image (based on the Intel oneAPI): https://github.com/beehive-lab/docker-tornado/blob/master/dockerFiles/Dockerfile.oneapi.intel.jdk17 

It needed a bit of configuration to run OpenCL programs.

**Comment by quantrpeter** [comment]
thanks

![image](https://github.com/beehive-lab/TornadoVM/assets/50471577/6c5ec659-ce5c-4063-938d-070f338e4ca1)

**Comment by quantrpeter** [comment]
after i set JAVA_HOME, i passed through but meet a new error. Also. apt-get install jdk won't set JAVA_HOME variable, this make tornadoVM broken.

![image](https://github.com/beehive-lab/TornadoVM/assets/50471577/1c243f75-ebe6-4bfa-822e-b624ff80b146)

after i do these, all error gone:

![image](https://github.com/beehive-lab/TornadoVM/assets/50471577/baf3f26b-6ce3-4bf7-a1d4-7f54293084d6)

thank you gentlemen
