### ISSUE TITLE
Improve code readbility and maintance with String Templates 

### ISSUE THREAD

**Issue by mikepapadim** [beehive-lab/TornadoVM#306]
**Is your feature request related to a problem? Please describe.**
The feature is related to code cleanup and readability. The codebase heavily uses  String concatenation for error and debug logging. 

**Describe the solution you'd like**
We can improve code readability and maintenance by replacing String manipulation with String Templates from JDK21.

**Describe alternatives you've considered**

**Additional context**
1) https://openjdk.org/jeps/430

**Comment by jjfumero** [comment]
Please, follow the template for feature request

**Comment by genzarchitect** [comment]
I would love to work on this. Can you assign it to me

**Comment by mikepapadim** [comment]
I added an example PR (#312) of what is expected in the scope of this task. 

I suggest going over one package at time (e.g., tornado-drivers, tornado-runtime etc), adopting String Templates were possible and opening a PR.

**Comment by jjfumero** [comment]
String templates are deprecated and removed from JDK 23.
https://mail.openjdk.org/pipermail/amber-spec-experts/2024-April/004106.html 

I will close this issue.
