### ISSUE TITLE
Add support for Copy-OUT only task-graphs using Batch Processing

### ISSUE THREAD

**Issue by jjfumero** [beehive-lab/TornadoVM#333]
**Is your feature request related to a problem? Please describe.**

Batch processing is also useful when having copy-outs only. This means that data on the target device is first allocated, there is no copy (data transfers) from the host to the device, but the execution is split to compute batches of size specified by the user. 
The runtime should only copy the partial arrays. 

This is partially supported, but the runtime gives incorrect results. My assumption is that there is an issue either with the setup parameters for the kernels, or for the copy-out.

**Comment by mairooni** [comment]
This was fixed in PR #376
