### ISSUE TITLE
Cannot install on Linux : No rule to make target 'jdk21'

### ISSUE THREAD

**Issue by R366Y** [beehive-lab/TornadoVM#349]
Thank you for taking the time to submit a bug report. Please fill the following template with your report to help our team to fix and/or propose solutions. 

---------------------------------------------------------------------

### Describe the bug 
I'm trying to install tornadoVM following the tutorial [](https://tornadovm.readthedocs.io/en/latest/installation.html)
I have linux jdk21 installed : /usr/lib/jvm/jdk-21-oracle-x64

### How To Reproduce
git cloned master branch
```
cd TornadoVM/bin
./tornadovm-installer --jdk jdk21 --backend opencl,ptx
_... downloaded some stuff..._
Checking dependency: cmake-3.25.2-linux-x86_64.tar.gz

Checking dependency: apache-maven-3.9.3-bin.tar.gz

Checking dependency: jdk-21_linux-x64_bin.tar.gz
make: *** No rule to make target 'jdk21'.  Stop.
 ------------------------------------------
        TornadoVM installation done        
 ------------------------------------------
Creating source file ......................
........................................[ok]
 
 
To run TornadoVM, first run `source setvars.sh`
```

### Computing system setup (please complete the following information):
 - OS: Linux  6.5.0-10022-tuxedo #26 SMP PREEMPT_DYNAMIC Thu Jan 18 02:29:42 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
(Ubuntu 22.04 LTS)

 - If applicable, PTX and CUDA Driver versions:
Cuda compilation tools, release 11.5, V11.5.119
Build cuda_11.5.r11.5/compiler.30672275_0

 - TornadoVM commit id: commit 20f33597d4f277b1544958a921ec1c3a056dec2c

### Additional context

---------------------------------------------------------------------

**Comment by stratika** [comment]
hi @R366Y, my guess is that the script breaks because you invoke it from within the bin directory, and then it cannot find the Makefile.

You can try to run the installer script, as follows:

```bash
cd TornadoVM
./bin/tornadovm-installer --jdk jdk21 --backend opencl,ptx
```

**Comment by R366Y** [comment]
It worked! thank you very much and sorry for the dumb question.

**Comment by stratika** [comment]
Sure, no problem. We can update the script, but in this case the script should be aware of where is the root directory of the project.
