### ISSUE TITLE
Can the whole repo be shared with ASL2.0/MIT

### ISSUE THREAD

**Issue by sirinath** [beehive-lab/TornadoVM#42]
**Is your feature request related to a problem? Please describe.**
Can part which is GPL be relicensed under ASL2.0/MIT

**Describe the solution you'd like**
Whole repo under ASL2.0/MIT

**Comment by jjfumero** [comment]
Hi @sirinath.

No, currently it cannot be re-licensed. TornadoVM extends the GraalVM JIT compiler (which is also GPLv2). Therefore, the TornadoVM JIT compiler is also GPLv2.

**Comment by sirinath** [comment]
GraalVM has assembly exception. So other than modification of the GraalVM itself can be relicensed.

**Comment by kotselidis** [comment]
TornadoVM modifies the Graal compiler (some optimisations at least) hence the GPL inheritance.

**Comment by sirinath** [comment]
Maybe the GPL+CE can be limited to the modified part which perhaps can be isolated into a sperate module (say `Tornado-graalvm`) while Tornado specific code can be separately licensed.

**Comment by kotselidis** [comment]
Yes, we are currently looking into it.

**Comment by jjfumero** [comment]
Currently, the licenses of TornadoVM components are as follows:

|  Module | License  |
|---|---|
| Tornado-API       |  [![License: GPL v2](https://img.shields.io/badge/License-GPL%20v2-blue.svg)](https://github.com/beehive-lab/TornadoVM/blob/master/LICENSE_GPLv2CEl) + CLASSPATH Exception |
| Tornado-Runtime   |  [![License: GPL v2](https://img.shields.io/badge/License-GPL%20v2-blue.svg)](https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html)   |
| Tornado-Assembly  |  [![License: GPL v2](https://img.shields.io/badge/License-GPL%20v2-blue.svg)](https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html)  |
| Tornado-Drivers   |  [![License: GPL v2](https://img.shields.io/badge/License-GPL%20v2-blue.svg)](https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html)   |
| Tornado-Drivers-OpenCL-Headers |  [![License: MIT](https://img.shields.io/badge/License-MIT%20-orange.svg)](https://github.com/KhronosGroup/OpenCL-Headers/blob/master/LICENSE) |
| Tornado-scripts   |  [![License: GPL v2](https://img.shields.io/badge/License-GPL%20v2-blue.svg)](https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html)   |
| Tornado-Annotation|  [![License](https://img.shields.io/badge/License-Apache%202.0-red.svg)](hhttps://github.com/beehive-lab/TornadoVM/blob/master/LICENSE_APACHE2) |
| Tornado-Unittests |  [![License](https://img.shields.io/badge/License-Apache%202.0-red.svg)](https://github.com/beehive-lab/TornadoVM/blob/master/LICENSE_APACHE2)  |
| Tornado-Benchmarks|  [![License](https://img.shields.io/badge/License-Apache%202.0-red.svg)](https://github.com/beehive-lab/TornadoVM/blob/master/LICENSE_APACHE2)  |
| Tornado-Examples  |  [![License](https://img.shields.io/badge/License-Apache%202.0-red.svg)](https://github.com/beehive-lab/TornadoVM/blob/master/LICENSE_APACHE2)   |
| Tornado-Matrices  |  [![License](https://img.shields.io/badge/License-Apache%202.0-red.svg)](https://github.com/beehive-lab/TornadoVM/blob/master/LICENSE_APACHE2)  |
| JNI Libraries (OpenCL, PTX and LevelZero)  |  [![License](https://img.shields.io/badge/License-MIT%20-orange.svg)](https://mit-license.org/)  |


Hope this is useful. 

I will close the issue. Please, if you have more questions, feel free to open new issues.
