### ISSUE TITLE
Join a Foundation like ASF

### ISSUE THREAD

**Issue by sirinath** [beehive-lab/TornadoVM#43]
Many research projects do not have continuity. 

Joining a foundation like ASF may help the long term stability and viability of TornadoVM

**Comment by jjfumero** [comment]
TornadoVM cannot join Apache Foundation due to its license. Part of the project is under the GPLv2 (e.g., the JIT compiler, and the runtime system).

**Comment by sirinath** [comment]
There is Eclipse Foundation, Linux Foundation, Cloud Native Computing Foundation, etc.

**Comment by kotselidis** [comment]
We are currently exploring different options regarding joining a foundation. Hopefully, during 2021 we will be in position to announce any taken decisions.

**Comment by hmf** [comment]
Or cerate your own :-)

**Comment by jjfumero** [comment]
I will close this issue. Please, feel free to open new issues for more questions, features, and bug reports.
