### ISSUE TITLE
OpenCL script support ?

### ISSUE THREAD

**Issue by eix128** [beehive-lab/TornadoVM#47]
Hi , is there any high level library/example code that imports existing OpenCL scripts ?
Also for shaders ?
I want to import my old OpenCL Libraries to TornadoVM.
So i can migrate my old C++ / OpenCL apps to TornadoVM easy...

**Comment by jjfumero** [comment]
@eix128 , Thank you for your interest in TornadoVM. Currently, we cannot import OpenCL directly. Although it is relatively easy to modify. 

Here's an example of an OpenCL kernel for TornadoVM:

https://github.com/beehive-lab/TornadoVM/blob/master/assembly/src/examples/generated/add2.cl 

```OpenCL
#pragma OPENCL EXTENSION cl_khr_fp64 : enable  
__kernel void add(__global uchar *_heap_base,     // global memory - TornadoVM Heap
                ulong _frame_base, 
                __constant uchar *_constant_region,     
                __local uchar *_local_region,            
                __global int *_atomics) 
{
    __global ulong *frame = (__global ulong *) &_heap_base[_frame_base];    // Obtain the stack-frame from Java
    ulong4 args = vload4(0, &frame[3]);          // Obtain the list of parameters

    __global double* inputA = (__global int *) (args.x + 24);
    __global double* inputB = (__global int *) (args.y + 24);
    __global double* output = (__global int *) (args.z + 24);

    // Existing OpenCL Code
    size_t idx = get_global_id(0);
    output[idx] = inputA[idx] + inputB[idx];   
}
```

Then, we have an API to load pre-compiled OpenCL. Here's an example:

https://github.com/beehive-lab/TornadoVM/blob/master/unittests/src/main/java/uk/ac/manchester/tornado/unittests/prebuilt/PrebuiltTest.java#L71-L103


Additionally, we are extending the TornadoVM API to easily create compute-kernels in a similar way to OpenCL, but in Java. This API will be released in 2 months, March 2021. Stay tuned.

**Comment by jjfumero** [comment]
I am closing this issue. If you have more questions, please, feel free to open another issue.
