### ISSUE TITLE
Can not install temurin-jdk-21 on windows using installation script

### ISSUE THREAD

**Issue by andrii0lomakin** [beehive-lab/TornadoVM#471]
If I run the installation script on Windows with JDK ` temurin-jdk-21` I get the result:
```
JDK {jdk} not configured for this OS/ machine configuration: {self.osPlatform}/ {self.hardware}
```
Also, installation instructions are incorrect on Windows, at least on my machine, I need to run
```
python  ./bin/tornadovm-installer
```
Not just the installer command.

**Comment by jjfumero** [comment]
Thanks @andrii0lomakin  for the report. We haven't included Temurin for Windows. Contributions are very welcome ;-)

**Comment by andrii0lomakin** [comment]
Would it not be reasonable to add a warning and exit in such a case?
In general, the installation routine is quite user-friendly.
