### ISSUE TITLE
Double addition of inputs in PrintfNode prevents inlining and as result debuggin

### ISSUE THREAD

**Issue by andrii0lomakin** [beehive-lab/TornadoVM#506]
During the addition of PrintfNode, all its input usages are also registered in the constructor because of the calling of `NodeList#set` method.
After that, it obviously added to the graph of operations by calling ` b.add(b.append(print mode));.`

That causes a second attempt to add printf inputs to the graph. This causes side effect - argument is used as a parameter of printf registers printf extra usage twice, so as a result during inlining, inputs of two printf nodes, instead of one, will be tried to be replaced by the new inlined node that causes an exception during compilation and as result inability to use printf for debugging.

Let us consider the example:

```
        var currentInputOffset = inputOffset + context.globalIdy * tensorLength + context.globalIdx;
        var localSnippet = context.allocateFloatLocalArray(64);

        float value = inputTensor.get(currentInputOffset);

        var localOffset = context.localGroupSizeX * context.localIdy;
        localSnippet[localOffset + context.localIdx] = value * value;

        if (context.localIdx == 0) {
            Debug.printf("%f\n", value);
        }
```

In the graph printf argument will be `FloatArray#get` method, which will be extracted in the plugin and then:
During construction, FloatArray#get will be added as input and then PrintfNode will be added as extra usage of FloatArray#get
![image](https://github.com/user-attachments/assets/6cd0aafe-c97a-4b3b-8200-1ad1f1ce1cdc)
But then after the call of ` b.add(b.append(print mode));.` , one more extra usage of `FloatArray#get` is added
![image](https://github.com/user-attachments/assets/3e44407a-234e-42b0-a010-70191280d0ac)
That causes an exception during `FloatArray#get` inlining because second attempt to replace the input of `second` printf node fails (because those nodes are the same instances):

```
Unable to build sketch for method: squareSumKernel(not found in inputs, usage: 64|printf)
uk.ac.manchester.tornado.api.exceptions.TornadoBailoutRuntimeException: Unable to build sketch for method: squareSumKernel(not found in inputs, usage: 64|printf)
	at tornado.runtime@1.0.6/uk.ac.manchester.tornado.runtime.sketcher.TornadoSketcher.buildSketch(TornadoSketcher.java:190)
	at tornado.runtime@1.0.6/uk.ac.manchester.tornado.runtime.sketcher.TornadoSketcher$TornadoSketcherCallable.call(TornadoSketcher.java:262)
	at tornado.runtime@1.0.6/uk.ac.manchester.tornado.runtime.sketcher.TornadoSketcher$TornadoSketcherCallable.call(TornadoSketcher.java:252)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

```

So the fix should be simple in a nutshell:
1. Use NodeList  NodeInputList(Node self, T[] elements)  instead of set in constructor.
2. There is no need to call both `append` and `add` methods in ` b.add(b.append(print mode));.`  The call to the add method is a no-op in this case because the node is already in the graph.

If I get everything right, I will provide the PR soon.

**Comment by jjfumero** [comment]
Thanks @andrii0lomakin for the report. We do not use this function and it is only partially supported for OpenCL. Improvemnts on this matter are very welcome.

**Comment by andrii0lomakin** [comment]
@jjfumero, what do you mean by partially supported? How do you debug kernels in such cases? Could you provide more information?
