### ISSUE TITLE
uk.ac.manchester.tornado.drivers.opencl.CLEvent incorrectly uses static field "buffer"

### ISSUE THREAD

**Issue by vsilaev** [beehive-lab/TornadoVM#52]
**Describe the bug**
uk.ac.manchester.tornado.drivers.opencl.CLEvent incorrectly uses static field `buffer`.

This static field is used from multiple instance methods like `readEventTime` and `getCLStatus`.
When multiple threads trying to execute separate `TaskSchedule` events are conflicting accessing this field. The race leads to clearing buffer right before reading value returned from JNI and code fails with empty buffer error.

The `buffer` should be a local variable of method rather than static field.

**How To Reproduce**
Run several Java threads each executing own `TaskSchedule.execute()`

**Expected behavior**
Running several separate `TaskSchedule`-s from different threads should work ok.

**Computing system setup (please complete the following information):**
 - OS: any
 - OpenCL Version 1.2
 - TornadoVM commit id: `develop` branch of 0.9 version

**Comment by jjfumero** [comment]
Thanks @vsilaev . Yes, that's a bug. The `buffer` variable should not be static.
Feel free to push a PR with this change.

**Comment by vsilaev** [comment]
Will do after previous PR review (windows support). It's hard for me to use separate Ubuntu instance -- my primary development currently is on Windows, and TornadoVM doesn't works on VM-s like Oracle VirtualBox or Microsoft Hyper-V due to lack of OpenCL devices (couldn't figure out how to set them up).

**Comment by jjfumero** [comment]
@vsilaev , are you providing this fix?
