### ISSUE TITLE
tornado-api compilation failure (duplicate module on upgrade module path)

### ISSUE THREAD

**Issue by gwinstanley** [beehive-lab/TornadoVM#524]
### Describe the bug 

Followed Installation for MacOS M1/M2/M3 instructions (using M2 Max), using installer command:
```
bin/tornadovm-installer --jdkHome $JAVA_HOME --backend opencl
```
with `JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-21.0.4+7/Contents/Home`

(**Note:** same result when using `bin/tornadovm-installer --jdk temurin-jdk-21 --backend opencl`, so not seemingly an anomaly of my pre-installed Java version).

Maven compilation of `tornado-api` module fails with error: _duplicate module on upgrade module path_

### How To Reproduce

Follow published instructions.

### Expected behavior 

Successful compilation as per instructions.

### Computing system setup (please complete the following information):
 - **OS:** macOS Sonoma 14.6
 - **OpenCL and Driver versions:** pre-installed macOS version (1.2?)
 - **PTX and CUDA Driver versions:** N/A
 - **Level Zero & SPIR-V Versions:** N/A
 - **TornadoVM commit id:** 22b4fed83

### Additional context

Found old #145 issue which exhibits something similar, but didn't help resolve.

[failure.log](https://github.com/user-attachments/files/16480974/failure0.log) (produced additional `mvn -X` flag)

**Comment by jjfumero** [comment]
It seems the Temurin download is failing. You can use any other OpenJDK-based distribution from the supported list:

The following command works:

```
./bin/tornadovm-installer --jdk jdk21 --backend=opencl
```

We recommend downloading the JDK using the TornadoVM installer script. This is because we need a specific version of JVMCI that integrates with the Graal Compiler Interface. 

```bash
➜  tornado git:(master) ✗ tornado --version
version=1.0.7-dev
branch=master
commit=22b4fed

Backends installed: 
	 - opencl
➜  tornado git:(master) ✗ tornado -version
WARNING: Using incubator modules: jdk.incubator.vector
java version "21.0.4" 2024-07-16 LTS
Java(TM) SE Runtime Environment (build 21.0.4+8-LTS-274)
Java HotSpot(TM) 64-Bit Server VM (build 21.0.4+8-LTS-274, mixed mode)
➜  tornado git:(master) ✗ tornado --devices 
WARNING: Using incubator modules: jdk.incubator.vector

Number of Tornado drivers: 1
Driver: OpenCL
  Total number of OpenCL devices  : 1
  Tornado device=0:0  (DEFAULT)
	OPENCL --  [Apple] -- Apple M2 Max
		Global Memory Size: 21.3 GB
		Local Memory Size: 32.0 KB
		Workgroup Dimensions: 3
		Total Number of Block Threads: [256]
		Max WorkGroup Configuration: [256, 256, 256]
		Device OpenCL C version: OpenCL C 1.2
```

**Comment by mikepapadim** [comment]
@gwinstanley this errors usually is related to havinb multiple graal jar version in the `graalJars` dir.

can you try to remove this directory and make the projet again?

**Comment by gwinstanley** [comment]
@mikepapadim good catch, that seems to be the problem. Removed that folder and now it builds successfully with the invocation as suggested by @jjfumero; many thanks, and hope to explore TornadoVM now...looks very interesting!
