### ISSUE TITLE
[bug] uk.ac.manchester.tornado.unittests.tasks.TestSingleTaskSingleDevice#testSimpleTaskOnDevice1 is failing on SpirV

### ISSUE THREAD

**Issue by andrii0lomakin** [beehive-lab/TornadoVM#536]
### Describe the bug 
Test uk.ac.manchester.tornado.unittests.tasks.TestSingleTaskSingleDevice#testSimpleTaskOnDevice1 is failing on SpirV backend

### How To Reproduce

`tornado-test -V uk.ac.manchester.tornado.unittests.tasks.TestSingleTaskSingleDevice`

```
Test: class uk.ac.manchester.tornado.unittests.tasks.TestSingleTaskSingleDevice
        Running test: testSimpleTask             ................  [PASS]
        Running test: testSimpleTaskOnDevice0    ................  [PASS]
        Running test: testSimpleTaskOnDevice1    ................  [FAILED]
                \_[REASON] [TornadoVM] Error - Recover option disabled
Test ran: 3, Failed: 1, Unsupported: 0

```
### Expected behavior 

Test is passed

### Computing system setup (please complete the following information):
 - OS: Ubuntu 22.04
 - OpenCL and Driver versions -  OpenCL version 3.0 , driver version - 23.43.27642.52
 - If applicable, Level Zero & SPIR-V Versions - 1.9.3
 - TornadoVM commit id - `35e7e550c`

**Comment by jjfumero** [comment]
How many SPIR-V devices do you see in your system? The failing test should select a second SPIR-V device.

**Comment by andrii0lomakin** [comment]
I have two GPU and CPU.

**Comment by jjfumero** [comment]
Test passing on a systems with Intel ARC + Intel Integrated GPU:

```
tornado-test -V uk.ac.manchester.tornado.unittests.tasks.TestSingleTaskSingleDevice

WARNING: Using incubator modules: jdk.incubator.vector

Test: class uk.ac.manchester.tornado.unittests.tasks.TestSingleTaskSingleDevice
        Running test: testSimpleTask             ................  [PASS] 
        Running test: testSimpleTaskOnDevice0    ................  [PASS] 
        Running test: testSimpleTaskOnDevice1    ................  [PASS] 
Test ran: 3, Failed: 0, Unsupported: 0

```

```
tornado --version
version=1.0.8-dev
branch=develop
commit=ed4b6ab

Backends installed: 
         - spirv
```

This could be a similar issue to #537 .
