### ISSUE TITLE
Wrong default compiler options: OpenCL 2.0 enforced

### ISSUE THREAD

**Issue by vsilaev** [beehive-lab/TornadoVM#55]
From documentation:

> 
> -Dtornado.opencl.compiler.options=LIST_OF_OPTIONS:
> It allows to pass the compile options specified by the OpenCL CLBuildProgram specification to TornadoVM at runtime. **By default it doesn't enable any**.

From code (`AbstractMetaData` constructor):
```java
openclCompilerOptions = (getProperty("tornado.opencl.compiler.options") == null) ? "-w -cl-std=CL2.0" : getProperty("tornado.opencl.compiler.options");
```

This prevents AMD OpenCL devices 1.1 / 1.2 from running (NVIDIA ignores this regardless of OpenCL 1.2 ver).

**Comment by stratika** [comment]
Can you please be more descriptive?

1) What is the OpenCL version of your AMD device? And which is the driver version that is installed?

2) Can you give more detail to reproduce the issue? (JDK version, example of a program that is failing)

**Comment by vsilaev** [comment]
> 2\. Can you give more detail to reproduce the issue? (JDK version, example of a program that is failing)

Just run any test with AMD device that supports OpenCL beyond 2.0 (I'm using AMD FirePro W5000 that is OpenCL 1.2 compatible).
You'll see smth. like:
```bash
Test: class uk.ac.manchester.tornado.unittests.arrays.TestArrays#testInitParallel
        Running test: testInitParallel           ................  [FAILED]
                \_[REASON] Error during code compilation with the OpenCL driver
Test ran: 1, Failed: 1
```

It's necessary to set explicit command-line argument to resolve the issue: `-Dtornado.opencl.compiler.options="-w"`
So either docs should be updated to reflect OpenCL 2.0 requirements, or defaults should be fixed.

**Comment by jjfumero** [comment]
That's correct. We introduced this when we start supporting atomics. The current way of atomics does not require this flag anymore, so we can remove it.

**Comment by jjfumero** [comment]
This is now fixed
