### ISSUE TITLE
TestArrays#testInitParallel on AMD - failed with '[REASON] [ERROR] reset() was called after warmup()'

### ISSUE THREAD

**Issue by vsilaev** [beehive-lab/TornadoVM#57]
When running `TestArrays#testInitParallel`  I get '[REASON] [ERROR] reset() was called after warmup()' exception thrown from `TornadoVM.compileTaskFromBytecodeToBinary`.

In fact, `TornadoTestBase.before` indeed reset ALL devices, but `TornadoVM.warmup` validates only one (VM-default ???) device. And if this device is different from SCHEDULE.TASK-device than it leads to an error (task device is changed via `s0.t0.device=0:1` command arg).

**Comment by jjfumero** [comment]
This is a bug. In fact, it happens with any device, not only for AMD. 

We will look into it. 

How to reproduce it? 

```bash 
tornado-test.py -V -pk --debug -J"-Ds0.t0.device=0:1" uk.ac.manchester.tornado.unittests.arrays.TestArrays#testInitParallel
```

Thank you for the report.

**Comment by vsilaev** [comment]
Btw, `-J` option is undocumented, and I had to alter `tornado` bash...

**Comment by jjfumero** [comment]
This PR also fixes this issue: https://github.com/beehive-lab/TornadoVM/pull/82 

You are right, the issue is that the default device is was not the selected device for the task.
