### ISSUE TITLE
ConcurentModificationException and JRE fatal error

### ISSUE THREAD

**Issue by nailh-boop** [beehive-lab/TornadoVM#581]
Thank you for taking the time to submit a bug report. Please fill the following template with your report to help our team to fix and/or propose solutions. 

---------------------------------------------------------------------

### Describe the bug 
Calling function from parallelStream for example like someSet.parallelStream().forEach(e->e.tornadoFunction()); cause errors.
Code works fine in a single stream.

ConcurentModificationException trace
```
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1598) ~[na:na]
	at tornado.runtime@1.0.7/uk.ac.manchester.tornado.runtime.tasks.TornadoTaskGraph.reuseDeviceBufferObject(TornadoTaskGraph.java:1063) ~[tornado-runtime-1.0.7.jar:na]
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[na:na]
	at tornado.runtime@1.0.7/uk.ac.manchester.tornado.runtime.tasks.TornadoTaskGraph.lockObjectsInMemory(TornadoTaskGraph.java:1074) ~[tornado-runtime-1.0.7.jar:na]
	at tornado.runtime@1.0.7/uk.ac.manchester.tornado.runtime.tasks.TornadoTaskGraph.transferToDevice(TornadoTaskGraph.java:969) ~[tornado-runtime-1.0.7.jar:na]
	at tornado.api@1.0.7/uk.ac.manchester.tornado.api.TaskGraph.transferToDevice(TaskGraph.java:683) ~[tornado-api-1.0.7.jar:na]
```
 JRE fatal error trace
```
	[JNI] Path\TornadoVM\TornadoVM\tornado-drivers\ptx-jni\target\windows-amd64-release\sources\source\PTXStream.cpp:181 in function: free_staging_block result = 1
	[JNI] Path\TornadoVM\TornadoVM\tornado-drivers\ptx-jni\target\windows-amd64-release\sources\source\PTXStream.cpp:181 in function: free_staging_block result = 1
	[JNI] Path\TornadoVM\TornadoVM\tornado-drivers\ptx-jni\target\windows-amd64-release\sources\source\PTXStream.cpp:181 in function: free_staging_block result = 1
	[JNI] Path\TornadoVM\TornadoVM\tornado-drivers\ptx-jni\target\windows-amd64-release\sources\source\PTXStream.cpp:181 in function: free_staging_block result = 1
	[JNI] Path\TornadoVM\TornadoVM\tornado-drivers\ptx-jni\target\windows-amd64-release\sources\source\PTXStream.cpp:181 in function: free_staging_block result = 1
[thread 15052 also had an error]
	[JNI] Path\TornadoVM\TornadoVM\tornado-drivers\ptx-jni\target\windows-amd64-release\sources\source\PTXStream.cpp:181 in function: free_staging_block result = 1
[thread 704 also had an error]
	[JNI] Path\TornadoVM\TornadoVM\tornado-drivers\ptx-jni\target\windows-amd64-release\sources\source\PTXStream.cpp:181 in function: free_staging_block result = 1
[thread 22184 also had an error]
	[JNI] Path\TornadoVM\TornadoVM\tornado-drivers\ptx-jni\target\windows-amd64-release\sources\source\PTXStream.cpp:181 in function: free_staging_block result = 1
[thread 15120 also had an error]
[thread 24464 also had an error]
	[JNI] Path\TornadoVM\TornadoVM\tornado-drivers\ptx-jni\target\windows-amd64-release\sources\source\PTXStream.cpp:181 in function: free_staging_block result = 1
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  [thread 25064 also had an error]EXCEPTION_ACCESS_VIOLATION (0xc0000005)
 at pc=0x00007fffed8562ad, pid=15384, tid=17740
#
# JRE version: OpenJDK Runtime Environment (21.0.2+13) (build 21.0.2+13-58)
# Java VM: OpenJDK 64-Bit Server VM (21.0.2+13-58, mixed mode, emulated-client, tiered, jvmci, parallel gc, windows-amd64)
# Problematic frame:
# C  [tornado-ptx.dll+0x62ad]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# Path\hs_err_pid15384.log
GPU: point (0.0,0.0,0.0) <=> CPU: point (9638150.158684263,1.860846326831648E7,53020.0)
ForkJoinPool.commonPool-worker-5
[55.673s][warning][os] Loading hsdis library failed
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```
### Computing system setup (please complete the following information):
 - OS: Windows 10
 - Cuda 12.5
 - TornadoVM commit id: 1.0.7-c712aa5

### Additional context

---------------------------------------------------------------------

**Comment by stratika** [comment]
hi @nailh-boop, can you please provide further information about your program or mention a test-case that presents this issue? With a test case, we will be able to check if we can reproduce the error.

**Comment by nailh-boop** [comment]
Test:
```
	@Test
	public void fatalError() {
		HashSet<String> s = new HashSet<String>();
		for(int i = 0;i<100;i++) {
			s.add(Integer.toString(i));
		}
		
		s.parallelStream().forEach(k->{
			try {
				IntersectionUtils.dummy();
			} catch (TornadoExecutionPlanException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		});
		System.out.println();
	}
```

dummy:
```
	public static void dummy() throws TornadoExecutionPlanException {
		DoubleArray tris1 = new DoubleArray(100);
		DoubleArray tris2 = new DoubleArray(100);
		DoubleArray res = new DoubleArray(10000);
		String threadName = Thread.currentThread().getName();
		TaskGraph taskGraph = new TaskGraph("s1") //
                .transferToDevice(DataTransferMode.EVERY_EXECUTION, tris1, tris2) //
                .task(threadName, IntersectionUtils::calculateCrossPoint, tris1, tris2, res) //
                .transferToHost(DataTransferMode.EVERY_EXECUTION, res);
        ImmutableTaskGraph immutableTaskGraph = taskGraph.snapshot();
        try (TornadoExecutionPlan executor = new TornadoExecutionPlan(immutableTaskGraph)) {
        	executor.execute();
        }
	}
```

calculateCrossPoint:
```
	private static void calculateCrossPoint(final DoubleArray a,final DoubleArray b,DoubleArray res) {
		
		for(@Parallel int i = 0; i < a.getSize();i+=9) {
			for(@Parallel int j = 0; j < b.getSize();j+=9) {
//				Double3 point = getTrianglesIntersectionPoint(new Double3(a.get(i),a.get(i+1),a.get(i+2)),new Double3(a.get(i+3),a.get(i+4),a.get(i+5)),
//						new Double3(a.get(i+6),a.get(i+7),a.get(i+8)),new Double3(b.get(j),b.get(j+1),b.get(j+2)),
//						new Double3(b.get(j+3),b.get(j+4),b.get(j+5)),new Double3(b.get(j+6),b.get(j+7),b.get(j+8)));
//				res.set((i/9 * b.getSize()/9 + j/9) * 3, point.getX());
//				res.set((i/9 * b.getSize()/9 + j/9) * 3 + 1, point.getY());
//				res.set((i/9 * b.getSize()/9 + j/9) * 3 + 2, point.getZ());
			}
		}
	}
```

**Comment by stratika** [comment]
hi @nailh-boop, I created a new Java class to test your issue. I tried on my macOS and it seems that the kernel is generated.

Here is the [Java class](https://github.com/stratika/TornadoVM/blob/issue/581/tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/multithreaded/TestIssue581.java).

Here is the output of the kernel that is executed 100 times. I report only the first time:
```bash
tornado-test --printKernel -V uk.ac.manchester.tornado.unittests.multithreaded.TestIssue581
tornado --jvm "-Xmx6g -Dtornado.recover.bailout=False -Dtornado.unittests.verbose=True -Dtornado.print.kernel=True "  -m  tornado.unittests/uk.ac.manchester.tornado.unittests.tools.TornadoTestRunner  --params "uk.ac.manchester.tornado.unittests.multithreaded.TestIssue581"
WARNING: Using incubator modules: jdk.incubator.vector

#pragma OPENCL EXTENSION cl_khr_fp16 : enable  
__kernel void calculateCrossPoint(__global long *_kernel_context, __constant uchar *_constant_region, __local uchar *_local_region, __global int *_atomics, __global uchar *a, __global uchar *b, __global uchar *res)
{
  int i_10, i_9, i_8, i_7, i_6, i_5, i_4, i_3, i_2, i_1, i_0, i_11; 

  // BLOCK 0
  i_0  =  get_global_size(0);
  i_1  =  get_global_size(1);
  i_2  =  get_global_id(0);
  i_3  =  i_2 << 3;
  i_4  =  i_3 + i_2;
  i_5  =  get_global_id(1);
  i_6  =  i_5 << 3;
  i_7  =  i_6 + i_5;
  // BLOCK 1 MERGES [0 5 ]
  i_8  =  i_7;
  for(;i_8 < 100;)
  {
    // BLOCK 2
    // BLOCK 3 MERGES [2 4 ]
    i_9  =  i_4;
    for(;i_9 < 100;)
    {
      // BLOCK 4
      i_10  =  i_0 + i_9;
      i_9  =  i_10;
    }  // B4
    // BLOCK 5
    i_11  =  i_1 + i_8;
    i_8  =  i_11;
  }  // B5
  // BLOCK 6
  return;
}  //  kernel
```

Can you try to run it? the test is in a new [branch](https://github.com/stratika/TornadoVM/blob/issue/581/tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/multithreaded/TestIssue581.java).

the command (after building TornadoVM) is:
```bash
tornado-test --printKernel -V uk.ac.manchester.tornado.unittests.multithreaded.TestIssue581
```

**Comment by stratika** [comment]
I tried to uncomment the comments from the `calculateCrossPoint` method, but something is missing. please update the description with your test case that triggers the issue.

**Comment by stratika** [comment]
hm, I see. It would be really helpful if you could find a simple test case to reproduce the problem.

**Comment by nailh-boop** [comment]
I get fatal error with test provided before in my project, but it works fine in your branch.

**Comment by stratika** [comment]
if the test works in your system, probably the integration with your project may affects it.

**Comment by nailh-boop** [comment]
I know that threads in my project modifying same resource. It may be device buffer object. Is it possible to disable reuseDeviceBufferObject logic to check. The main problem that error is inconsistent. It usually ends with fatal error halfway (I reduced number of elements to 10 and 5 kernels are printed in console before error appeared). Rarely test ends with ConcurentModificationException or without an issue.

**Comment by stratika** [comment]
If you want to try to run without reusing device buffers you can run with this jvm option:
--jvm="-Dtornado.reuse.device.buffers=False"

We have some [multi-threaded example tests](https://github.com/beehive-lab/TornadoVM/blob/master/tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/multithreaded/TestMultiThreadedExecutionPlans.java), that show how we are using the TornadoVM API in multi-threaded programs.

Let us know if this flag had any change.

**Comment by jjfumero** [comment]
Just a though here: does this break only for the PTX? We are currently fixing a concurrency issue related to memory management for the PTX backend, so this could be related. If it happens for all backends, it might be a separated issue.

**Comment by nailh-boop** [comment]
Error remains without reusing device buffers, but appears less often. I can't build openCL backend, there are lots of "is not an internal or external command, executable program or batch file" statements in console.

**Comment by nailh-boop** [comment]
@stratika, @jjfumero here is part of the log for TestMultiThreadedExecutionPlans error.
```
Current thread (0x000001da37ede440):  JavaThread "Thread-12"        [_thread_in_native, id=10604, stack(0x000000cf6e800000,0x000000cf6e900000) (1024K)]

Stack: [0x000000cf6e800000,0x000000cf6e900000],  sp=0x000000cf6e8fee70,  free space=1019k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [tornado-ptx.dll+0x62ad]

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  uk.ac.manchester.tornado.drivers.ptx.PTXStream.cuDestroyStream([B)J+0 tornado.drivers.ptx@1.0.9-dev
j  uk.ac.manchester.tornado.drivers.ptx.PTXStream.cuDestroyStream()V+4 tornado.drivers.ptx@1.0.9-dev
j  uk.ac.manchester.tornado.drivers.ptx.PTXStreamTable$ThreadStreamTable.cleanup(J)V+38 tornado.drivers.ptx@1.0.9-dev
j  uk.ac.manchester.tornado.drivers.ptx.PTXStreamTable.cleanup(Luk/ac/manchester/tornado/drivers/ptx/PTXDevice;)V+32 tornado.drivers.ptx@1.0.9-dev
j  uk.ac.manchester.tornado.drivers.ptx.PTXDeviceContext.reset(J)V+26 tornado.drivers.ptx@1.0.9-dev
j  uk.ac.manchester.tornado.runtime.tasks.TornadoTaskGraph.free()V+54 tornado.runtime@1.0.9-dev
j  uk.ac.manchester.tornado.runtime.tasks.TornadoTaskGraph.freeDeviceMemory()V+1 tornado.runtime@1.0.9-dev
j  uk.ac.manchester.tornado.api.TaskGraph.freeDeviceMemory()V+4 tornado.api@1.0.9-dev
j  uk.ac.manchester.tornado.api.ImmutableTaskGraph.freeDeviceMemory()V+4 tornado.api@1.0.9-dev
j  uk.ac.manchester.tornado.api.TornadoExecutor$$Lambda+0x000001dbfba57368.accept(Ljava/lang/Object;)V+4 tornado.api@1.0.9-dev
j  java.util.ArrayList.forEach(Ljava/util/function/Consumer;)V+46 java.base@21.0.1
j  uk.ac.manchester.tornado.api.TornadoExecutor.freeDeviceMemory()V+9 tornado.api@1.0.9-dev
j  uk.ac.manchester.tornado.api.TornadoExecutionPlan.close()V+4 tornado.api@1.0.9-dev
j  uk.ac.manchester.tornado.unittests.multithreaded.TestMultiThreadedExecutionPlans.compute(IIZ)V+130 tornado.unittests@1.0.9-dev
j  uk.ac.manchester.tornado.unittests.multithreaded.TestMultiThreadedExecutionPlans.lambda$test04$7(I)V+8 tornado.unittests@1.0.9-dev
j  uk.ac.manchester.tornado.unittests.multithreaded.TestMultiThreadedExecutionPlans$$Lambda+0x000001dbfbbe2700.run()V+8 tornado.unittests@1.0.9-dev
j  java.lang.Thread.runWith(Ljava/lang/Object;Ljava/lang/Runnable;)V+5 java.base@21.0.1
j  java.lang.Thread.run()V+19 java.base@21.0.1
v  ~StubRoutines::call_stub 0x000001da0f7e0fff

siginfo: EXCEPTION_ACCESS_VIOLATION (0xc0000005), reading address 0x0000000000000008

```

**Comment by jjfumero** [comment]
We just pushed a fix for the memory management in the PTX backend. 
https://github.com/beehive-lab/TornadoVM/commit/9c3f8ce7eb917f30788710b390c07a072ecc49fb 

This might help.

**Comment by nailh-boop** [comment]
Issue fixed for the TestMultiThreadedExecutionPlans.
In my project issue fixed only with --jvm="-Dtornado.reuse.device.buffers=False" flag.
Is it possible that error appears because of IDE?

**Comment by jjfumero** [comment]
Not sure. It could be a bug in TornadoVM. 

So the flag `--jvm="-Dtornado.reuse.device.buffers=False"` is for internal development and we do not recommend to set it to False. What TornadoVM does when this is set to false is to force `deviceAlloc` and `deviceFree` buffers every time an execution plan is launched. When it is set to `true`, then TornadoVM marks free buffers and reuses already allocated buffers when possible.

**Comment by nailh-boop** [comment]
I understand, but it's not work otherwise. When buffers are deleted? In PTXStream.cpp there is a queue which hold unused pinned memory and as soon as cuDestroyStream called the entire queue is cleared. Is it possible that stream is deleted while pinned memory is used by other streams?

**Comment by jjfumero** [comment]
We fixed this class recently. Are you using the latest TornadoVM version from the `master` branch?

**Comment by nailh-boop** [comment]
Yes I do, may be there is a problem with the integraton in my project. I'm using jdk-21,builded tornadoVM on my machine and added java flags to VM options.Am I missing something? My main concern that all problems disappear when I call tornadoVM function from single stream and there is no problems with running tornado tests from the console.

**Comment by jjfumero** [comment]
Is it possible to share the project with instructions, so we could try to replicate it?

**Comment by nailh-boop** [comment]
The project is too big. I will try to make a smaller project to share.

**Comment by nailh-boop** [comment]
The error appear less frequently with -XX:+UseG1GC instead of -XX:+UseParallelGC.

**Comment by jjfumero** [comment]
Thanks @nailh-boop . I get a different error regarding with the modification of an internal data structure. We will take a look. 

Concerning the PTX, I think we have never tried to run on multiple PTX devices (different NVIDIA GPUs at the same time). The reason you see the device names is that TornadoVM registers the device information in the runtime (name, max memory, max threads, local memory, etc) to make pass to the compiler and runtime to make better decisions. This is normal.

**Comment by jjfumero** [comment]
BTW, I noticed you are using the previous version. Just be sure you use the `master` branch:

```xml
 18     <dependencies>
 19         <dependency>
 20             <groupId>tornado</groupId>
 21             <artifactId>tornado-api</artifactId>
 22             <version>1.0.9-dev</version>
 23         </dependency>
 24 
 25         <dependency>
 26             <groupId>tornado</groupId>
 27             <artifactId>tornado-matrices</artifactId>
 28             <version>1.0.9-dev</version>
 29         </dependency>
 30     </dependencies>
```

**Comment by nailh-boop** [comment]
Thanks i've changed the version. I have only one NVIDIA GPU, but two are registred pointing to the same device, that's may be reason for the ConcurentModificationException.

**Comment by jjfumero** [comment]
Ok that's an interesting finding. It seems there is a bug in TornadoVM. We will look into it.

**Comment by nailh-boop** [comment]
Temporal solution. In file PTXBackendImpl.java change getAllDevices() with code below.
```
    private synchronized  void initAllDevices(){
        if (devices == null) {
            devices = new ArrayList<>();
            for (int i = 0; i < getNumDevices(); i++) {
                devices.add(backends[i].getDeviceContext().toDevice());
            }
        }
    }

    @Override
    public List<TornadoDevice> getAllDevices() {
        if (devices == null) {
            initAllDevices();
        }
        return devices;
    }
```

**Comment by stratika** [comment]
> Temporal solution. In file PTXBackendImpl.java change getAllDevices() with code below.

Does this solve your issue?

**Comment by nailh-boop** [comment]
Yes it does. There was a possibility that multiple streams executed loop, so even with single GPU multiple objects were added. I think there's another problem like this somewhere because I have a function which stucks in parallel streams but works fine in a single stream.

**Comment by stratika** [comment]
thank you for the report. we will patch it, let us know if you have any further findings. it's very helpful.

**Comment by nailh-boop** [comment]
You are wellcome, I will let you know.
