### ISSUE TITLE
Error when using BigDecimal's compareTo method in TornadoVM

### ISSUE THREAD

**Issue by ruthven93** [beehive-lab/TornadoVM#585]
---------------------------------------------------------------------

### I encountered an error while using the compareTo method of BigDecimal in TornadoVM. Below are the error message and my simple test program：
WARNING: Using incubator modules: jdk.incubator.vector
WARNING: Code Bailout to Java sequential. Use --debug to see the reason
Exception in thread "main" uk.ac.manchester.tornado.api.exceptions.TornadoBailoutRuntimeException: Unable to build sketch for method: loop (uk.ac.manchester.tornado.api.exceptions.TornadoInternalError: unimplemented)
	at tornado.runtime@1.0.9-dev/uk.ac.manchester.tornado.runtime.sketcher.TornadoSketcher.buildSketch(TornadoSketcher.java:191)
	at tornado.runtime@1.0.9-dev/uk.ac.manchester.tornado.runtime.sketcher.TornadoSketcher$TornadoSketcherCallable.call(TornadoSketcher.java:263)
	at tornado.runtime@1.0.9-dev/uk.ac.manchester.tornado.runtime.sketcher.TornadoSketcher$TornadoSketcherCallable.call(TornadoSketcher.java:253)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
### My simple test program

```
public class Main {
    public static void loop() {
        BigDecimal test1 = new BigDecimal(10000);
        BigDecimal test2 = new BigDecimal(20000);
        int j = 0;
        if (test1.compareTo(test2) == -1) {
            j++;
        }
    }

    public static void run() {
        TaskGraph taskGraph = new TaskGraph("test-tornado")
                .task("mxm", Main::loop);

        ImmutableTaskGraph immutableTaskGraph = taskGraph.snapshot();
        try (TornadoExecutionPlan executionPlan = new TornadoExecutionPlan(immutableTaskGraph)) {
            TornadoExecutionResult executionResult = executionPlan.execute();
        } catch (TornadoExecutionPlanException e) {
            e.printStackTrace();
        }
    }
    
    public static void main(String[] args) {
        run();
    }
}
```

### Computing system setup (please complete the following information):
 - OS: Kylin V10 SP1  aarch64
 - OpenCL and Driver versions
  Number of Tornado drivers: 1
  Driver: OpenCL
    Total number of OpenCL devices  : 2
    Tornado device=0:0  (DEFAULT)
	  OPENCL --  [Phytium] -- PhytiumVR A-Series AXT-16-512
		  Global Memory Size: 1.8 GB
		  Local Memory Size: 28.0 KB
		  Workgroup Dimensions: 3
		  Total Number of Block Threads: [1024]
		  Max WorkGroup Configuration: [1024, 1024, 1024]
		  Device OpenCL C version: OpenCL C 3.0
  
    Tornado device=0:1
	  OPENCL --  [Portable Computing Language] -- pthread-0x663
		  Global Memory Size: 13.5 GB
		  Local Memory Size: 1.0 MB
		  Workgroup Dimensions: 3
		  Total Number of Block Threads: [4096]
		  Max WorkGroup Configuration: [4096, 4096, 4096]
		  Device OpenCL C version: OpenCL C 1.2 pocl

---------------------------------------------------------------------

**Comment by jjfumero** [comment]
Hi @ruthven93 , thanks for the report. `BigDecimal` objects are not supported. 

All supported types are in this package:
https://github.com/beehive-lab/TornadoVM/tree/master/tornado-api/src/main/java/uk/ac/manchester/tornado/api/types

**Comment by ruthven93** [comment]
> Hi @ruthven93 , thanks for the report. `BigDecimal` objects are not supported.
> 
> All supported types are in this package: https://github.com/beehive-lab/TornadoVM/tree/master/tornado-api/src/main/java/uk/ac/manchester/tornado/api/types

Okay, I understand. Thank you for your response.
