### ISSUE TITLE
Deadlock/program stuck while calling function from parallelStream

### ISSUE THREAD

**Issue by nailh-boop** [beehive-lab/TornadoVM#588]
### Describe the bug 
Program will stuck and never finish, if function called from parallelStream. There is no problem when function called from stream.

### How To Reproduce

```
	public void Error() {
		List<String> s = new ArrayList<String>();
		for(int i = 0;i<4;i++) {
			s.add(Integer.toString(i));
		}
		
		s.parallelStream().forEach(k->{
			try {
				IntersectionUtils.dummy();
				System.out.println(k);
			} catch (TornadoExecutionPlanException e) {
				// TODO Auto-generated catch block
				//e.printStackTrace();
			}
		});
		System.out.println();
	}
```
Here is the class with required functions.
[IntersectionUtils.zip](https://github.com/user-attachments/files/17643787/IntersectionUtils.zip)

### Computing system setup (please complete the following information):
 - OS:Windows 10
 - compute capability of 8.9, cuda 12.5
 - commit id 1.0.9-dev-3c0de66
### Additional context

---------------------------------------------------------------------

**Comment by jjfumero** [comment]
We pushed a fix: https://github.com/beehive-lab/TornadoVM/commit/0d4425264ffe0633ea79c8aba91233591059d3fd 

You can check latest `master` branch. Please let us know if you encounter more issues.

**Comment by nailh-boop** [comment]
Thanks I will try the new patch, I fixed this issue few days ago. The program works fine after I've changed function call for function body.
