### ISSUE TITLE
Different (incorrect) results when running with GPU compared to sequential

### ISSUE THREAD

**Issue by brucejohnson** [beehive-lab/TornadoVM#67]
**Describe the bug**
When testing an implementation of an FFT with TornadoVM I found that I am getting different (and incorrect) results when running the exact same method on the GPU as compared to calling it directly.  I narrowed the code down to a simple test case which sets up an array of numbers, retrieves them in sets of 8 values, multiplies them by 10, and puts them back into shuffled locations relative to where they are read from.  In the output below it appears that line numbered 2 (and 6) in GPU mode have 10x the number that has been written into the location it reads from rather than 10x the number that was originally there.  So it is 200 (10 x 20) rather than 10 (10 x 1).  Note that the output is in pairs as original FFT code is to support real/imaginary pairs in alternate locations.

Output in sequential mode:

    0   0.000   0.000
    1  20.000 160.000
    2  10.000  80.000
    3  30.000 240.000
    4  40.000 320.000
    5  60.000 480.000
    6  50.000 400.000
    7  70.000 560.000

Output in gpu mode

     0   0.000   0.000
     1  20.000 160.000
     2 200.000 1600.000
     3  30.000 240.000
     4  40.000 320.000
     5  60.000 480.000
     6 600.000 4800.000
     7  70.000 560.000

**How To Reproduce**
Compile the attached ShuffleTest.java file and run:
 tornado -cp target/example-1.0-SNAPSHOT.jar org.nmrfx.tornado.ShuffleTest seq > seq.txt
 tornado -cp target/example-1.0-SNAPSHOT.jar org.nmrfx.tornado.ShuffleTest gpu > gpu.txt
Compare the two output files

[ShuffleTest.txt](https://github.com/beehive-lab/TornadoVM/files/6017943/ShuffleTest.txt)

**Expected behavior**
The output in gpu.txt and seq.txt should be the same.

**Computing system setup (please complete the following information):**
 - OS:  Ubuntu 20
 - OpenCL Version : Using PTX
 - TornadoVM commit id: 5022bea

**Additional context**

Number of Tornado drivers: 1
Total number of PTX devices  : 3
Tornado device=0:0
	PTX -- GeForce RTX 2080 SUPER
		Global Memory Size: 7.8 GB
		Local Memory Size: 48.0 KB
		Workgroup Dimensions: 3
		Max WorkGroup Configuration: [1024, 1024, 64]
		Device OpenCL C version: N/A

**Comment by jjfumero** [comment]
Thank you for the report. We will look into this.

**Comment by gigiblender** [comment]
This is now fixed. I will now close this issue.
