### ISSUE TITLE
TornadoVM does not fully respect the SSA form during LIR building 

### ISSUE THREAD

**Issue by gigiblender** [beehive-lab/TornadoVM#74]
In case of `if` conditions we respect the SSA:
```
z_295  =  i_159 == i_4;
  if(z_295)
  {
    ....
  ```
  
  In case of `for` loops, I am not sure we do:
```
i_4  =  i_3;
  for(;i_4 < 8;)  {
    ....
    i_15  =  i_14 + i_4;
    i_4  =  i_15;
  }
```

I am not sure this is an actual problem and open this issue for discussion.

**Comment by jjfumero** [comment]
Thanks for the report @gigiblender. We will need all in SSA for the SPIRV backend, . 

Maybe an assignment is missing:

```java 
OCLLIRStmt.AssignStmt(result, value)
```

So, when we process the order of the loop:

https://github.com/mikepapadim/TornadoVM/blob/master/drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/compiler/OCLCompilationResultBuilder.java#L203-L243

We would need to add this instruction before evaluating the `condition` and pass the result value of the assignment to the loop-condition. Would that solve the problem?

**Comment by jjfumero** [comment]
This was not an issue for the SPIR-V backend. Shall we close this issue, @gigiblender ?

**Comment by jjfumero** [comment]
@gigiblender , this does seem to be an issue with the SPIRV, which respects the SSA representation. I will close this issue.
