### ISSUE TITLE
Enhance Reduction Operators for TornadoMath functions

### ISSUE THREAD

**Issue by stratika** [beehive-lab/TornadoVM#79]
I tried in [`TestReductionsDoubles`](https://github.com/beehive-lab/TornadoVM/blob/master/unittests/src/main/java/uk/ac/manchester/tornado/unittests/reductions/TestReductionsDoubles.java) to replace `Math.max()` with `TornadoMath.max()`.

```java
private static void maxReductionAnnotation(double[] input, @Reduce double[] result) {
        for (@Parallel int i = 0; i < input.length; i++) {
            result[0] = Math.max(result[0], input[i]);
        }
}
```

```java
private static void maxReductionAnnotation(double[] input, @Reduce double[] result) {
        for (@Parallel int i = 0; i < input.length; i++) {
            result[0] = TornadoMath.max(result[0], input[i]);
        }
}
```
This replacement resulted in the following error.

```
Test: class uk.ac.manchester.tornado.unittests.reductions.TestReductionsDoubles#testMaxReduction
	Running test: testMaxReduction           ................  [FAILED] 
		\_[REASON] [ERROR] Automatic reduce operation not supported yet: 17|OCLFPBinaryIntrinsic
	uk.ac.manchester.tornado.api.exceptions.TornadoRuntimeException: [ERROR] Automatic reduce operation not supported yet: 17|OCLFPBinaryIntrinsic
	at uk.ac.manchester.tornado.runtime.analyzer.ReduceCodeAnalysis.getReduceOperation(ReduceCodeAnalysis.java:117)
```

The same issue is shown for other operations (e.g. min, pow...)

So, the feature is to **update the [`ReduceCodeAnalysis`](https://github.com/beehive-lab/TornadoVM/blob/master/runtime/src/main/java/uk/ac/manchester/tornado/runtime/analyzer/ReduceCodeAnalysis.java) to support the operators in TornadoMath package**.

**How to test:**

Change the `Math.max()` with `TornadoMath.max()` and run:

```
$ make
$ tornado -ea -Dtornado.unittests.verbose=True -Xmx6g -Dtornado.recover.bailout=False uk.ac.manchester.tornado.unittests.tools.TornadoTestRunner  uk.ac.manchester.tornado.unittests.reductions.TestReductionsDoubles#testMaxReduction
```

**Comment by jjfumero** [comment]
Thank you for the report @stratika. Let's schedule this enhancement for TornadoVM 0.10 .
