### ISSUE TITLE
Make OCLKind and PTXKind consistent for LocalArrayNodes

### ISSUE THREAD

**Issue by stratika** [beehive-lab/TornadoVM#89]
**Describe the feature**
There is an inconsistency between the OpenCL and the PTX backends. 
The inconsistency is observed in the `generate` method of the `LocalArrayNode`. Prior to the `TornadoVMContext` features, this node was used only from the snippets. So, we could use the constructor that uses the `ResolvedJavaType` field. Now, that we append this node from the CompilerGraphPlugins, we use a second constructor that uses the `JavaKind` instead of the `ResolvedJavaType`. 

This change in the [OpenCL backend](https://github.com/beehive-lab/TornadoVM/blob/master/drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/nodes/LocalArrayNode.java) was ok, as the `generate` method used the following line to obtain the `LIRKind`.
```
// line in the generate method
LIRKind lirKind = LIRKind.value(gen.getLIRGeneratorTool().target().arch.getWordKind());
```

However, in the [PTX backend](https://github.com/beehive-lab/TornadoVM/blob/master/drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/nodes/LocalArrayNode.java) the `LIRKind` was obtained by the `kind` that was initialized in the constructor from the `ResolvedJavaType`.
```
// line in the constructor
this.kind = PTXKind.fromResolvedJavaType(elementType)

// line in the generate method
LIRKind lirKind = LIRKind.value(kind);
```

In order to make it work for the `TornadoVMContext`, I made the PTX generate method to use the `gen.getLIRGeneratorTool().target().arch.getWordKind()` similar to the OpenCL method. This seems to work for all unit-tests.

Feature description:
After discussion with @jjfumero and @gigiblender, we decided to merge the new API, and open this issue for this feature:
**Make the LIRKind to be obtained by the kind (OCLKind or PTXKind).**

To do this, we can create a new method in the [OCLKind](https://github.com/beehive-lab/TornadoVM/blob/master/drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/lir/OCLKind.java), [PTXKind](https://github.com/beehive-lab/TornadoVM/blob/master/drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/lir/PTXKind.java) classes that resolves the backend kind from the JavaKind. For example:

```
public static OCLKind fromResolvedJavaKind(JavaKind javaKind);

public static PTXKind fromResolvedJavaKind(JavaKind javaKind);
```

**Comment by jjfumero** [comment]
I think the way to go is by getting word kind from the constructor. For that, we can add a new method in OCLKind from type `JavaKind` to `OCLKind`, if possible.
